local runtime:
		g++ -std=c++20 compare_words.cpp compare_runtime.cpp -Wall -g -o compare_test
		./compare_test
		rm compare_test

local compiled:
		g++ -std=c++20 compare_words.cpp compare_compiled.cpp -Wall -g -o compare_test
		./compare_test
		rm compare_test		