runtime:
		g++ -std=c++20 compare_runtime.cpp -Wall -g -o compare_test
		./compare_test
		rm compare_test

compiled:
		g++ -std=c++20 compare_compiled.cpp -Wall -g -o compare_test
		./compare_test
		rm compare_test		